databases:
  - name: pet-store
    databaseName: pet-store
    user: postgres

services:
  - type: web
    name: pet-store
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pet-store
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false